version: "3.2"

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "pedrina"
    ports:
      - "15432:5432"
    container_name: postgres-container

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "pedrina.alisson@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "123"
    ports:
      - "16543:80"
    depends_on:
      - postgres-compose
