version: "3.2"

services:
  twitter-producer:
    build: ../twitter-producer
    image: twitter-producer:latest
    ports:
      - "8761:8761"
    container_name: twitter-producer
    networks:
      - apedrina-network
  twitter-consumer:
    build: ../twitter-consumer
    image: twitter-consumer:latest
    ports:
      - "8888:8888"
    container_name: twitter-consumer
    networks:
      - apedrina-network

networks:
  apedrina-network:
    driver: bridge
